# Generated by Django 2.2.16 on 2021-10-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='projet',
        ),
    ]
