# Generated by Django 2.2.16 on 2021-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_facture_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entreprise',
            options={'ordering': ['nom_commercial'], 'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
        migrations.AlterField(
            model_name='service',
            name='type_de_service',
            field=models.CharField(choices=[('Développement', 'Développement'), ('licence', 'licence'), ('Hebergement', 'Hebergement'), ('Maintenance', 'Maintenance'), ('Conseil', 'Conseil'), ('SEO & SEA', 'SEO & SEA')], max_length=200),
        ),
    ]
