# Generated by Django 2.2.16 on 2021-10-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_entreprise_code_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix_HT',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('Payé', 'Payé'), ('En attente de paiement', 'En attente de paiement'), ('En retard', 'En retard')], max_length=200),
        ),
    ]
